module.exports = {
  up: function (queryInterface, Sequelize) {
    return [
      queryInterface.bulkInsert('users', [
        {name: "Jim Bailey",
          age: "34",
          sex: "Male",
          phone: "756-8990",
          email: "jim@email.com",
          tag_line: "'Whatever'",
          image: "https://s-i.huffpost.com/gen/1065394/images/o-DRAG-QUEENS-facebook.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Warrior Princess",
          age: "35",
          sex: "Female",
          phone: "123-3456",
          email: "xena@email.com",
          tag_line: "'Looking for a battle'",
          image: "https://vignette4.wikia.nocookie.net/warriorprincess/images/5/59/Xena_warrior_princess_by_xena_96-d56o27k.jpg/revision/latest?cb=20130815215113https://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpg https://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpghttps://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Todd Jones",
          age: "40",
          sex: "Male",
          phone: "556-7890",
          email: "toad@email.com",
          tag_line: "'Hey there!!'",
          image: "https://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Jared Fogle",
          age: "40",
          sex: "Male",
          phone: "334-7878",
          email: "jared@email.com",
          tag_line: "'How old r U?'",
          image: "https://the-hollywood-gossip-res.cloudinary.com/iu/s--FpbYh7Gu--/t_xlarge_p/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1489513996/jared-fogle-in-a-bowtie.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Popcorn Sutton",
          age: "65",
          sex: "Male",
          phone: "908-7878",
          email: "pop@email.com",
          tag_line: "'Know a good lawyer?'",
          image: "http://media-cdn.timesfreepress.com/img/photos/2014/06/05/866912_t300_t755_he12b112dc0f2a87c390507e9c8ab5039eedb0fe8.JPG",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Bob Marley",
          age: "36",
          sex: "Male",
          phone: "420-1212",
          email: "bob@email.com",
          tag_line: "'It's natural'",
          image: "https://i.pinimg.com/736x/7a/dc/ba/7adcba2fde48dab0adfdcc3efcf8e879--musique-reggae-bob-marley.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Jack Daniels",
          age: "24",
          sex: "Male",
          phone: "777-4501",
          email: "jack@email.com",
          tag_line: "'I need to grow up'",
          image: "https://katieholt1.files.wordpress.com/2010/10/oslo_passout.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Candy Cane",
          age: "23",
          sex: "Female",
          phone: "444-9988",
          email: "sugar@email.com",
          tag_line: "'Yes'",
          image: "https://img00.deviantart.net/2892/i/2008/094/2/4/drug_girl_by_aurorabeaupre.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Granny Moses",
          age: "80",
          sex: "Female",
          phone: "912-3900",
          email: "granny@email.com",
          tag_line: "'$&!% the police'",
          image: "https://i.pinimg.com/736x/63/f9/ea/63f9eaf4ff430456106e22abb9732d7b--irene-ryan-ryan-oneal.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Billy Graham",
          age: "98",
          sex: "Male",
          phone: "666-6666",
          email: "will@email.com",
          tag_line: "'God is watching'",
          image: "https://i.pinimg.com/736x/63/f9/ea/63f9eaf4ff430456106e22abb9732d7b--irene-ryan-ryan-oneal.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Angelina Jolie",
          age: "42",
          sex: "Female",
          phone: "355-6700",
          email: "ang@email.com",
          tag_line: "'Know a good baby sitter'",
          image: "https://www.thesun.co.uk/wp-content/uploads/2016/10/nintchdbpict000160735799.jpg?w=640",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Hunter Thompson",
          age: "65",
          sex: "Male",
          phone: "088-9999",
          email: "coke@email.com",
          tag_line: "'I need a drink'",
          image: "https://www.thesun.co.uk/wp-content/uploads/2016/10/nintchdbpict000160735799.jpg?w=640",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Elmer Fudd",
          age: "35",
          sex: "Male",
          phone: "705-0139",
          email: "fud@email.com",
          tag_line: "'I work for PETA'",
          image: "https://static.comicvine.com/uploads/original/11/111746/4352026-4927658174_981e6cd63e_z.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Casey Anthony",
          age: "31",
          sex: "Female",
          phone: "701-1257",
          email: "kc@email.com",
          tag_line: "'Where is my daughter?'",
          image: "https://static.comicvine.com/uploads/original/11/111746/4352026-4927658174_981e6cd63e_z.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Snoop Dawg",
          age: "46",
          sex: "Male",
          phone: "913-4200",
          email: "smoke@email.com",
          tag_line: "'I never inhale'",
          image: "http://www.chartattack.com/wp-content/uploads/2016/10/snoop-dogg-marijuana.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Martha Stewart",
          age: "70",
          sex: "Female",
          phone: "501-9930",
          email: "foodie@email.com",
          tag_line: "'What's insider trading?'",
          image: "http://a.abcnews.com/images/Entertainment/GTY_martha_stewart_sk_140306_16x9_608.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Jim Morrison",
          age: "27",
          sex: "Male",
          phone: "409-1970",
          email: "jim@email.com",
          tag_line: "'I am the lizard king'",
          image: "http://i.axs.com/2014/08/promoted-media-optimized_53e3a6f8954c3.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Kate Gosselin",
          age: "42",
          sex: "Female",
          phone: "222-1020",
          email: "kateplus8@email.com",
          tag_line: "'Where are my kids?'",
          image: "http://images.gawker.com/17iuol0zjbta5jpg/original.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Betty Bottle",
          age: "25",
          sex: "Female",
          phone: "191-1209",
          email: "betty@email.com",
          tag_line: "'I'll drink that!'",
          image: "http://tarabliss.com.au/wp-content/uploads/2013/03/PGG2P.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Janis Joplin",
          age: "27",
          sex: "Female",
          phone: "235-6509",
          email: "janis@email.com",
          tag_line: "'Hey Man!'",
          image: "http://d1wl13ohcvociy.cloudfront.net/wp-content/uploads/2015/09/tumblr_meyke7bh8u1rwkvi9o1_500.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Tina Turner",
          age: "65",
          sex: "Female",
          phone: "222-5126",
          email: "tina@email.com",
          tag_line: "'What's love gotta do with it?'",
          image: "https://i.pinimg.com/originals/46/cb/bf/46cbbf36cedb467f8b3d9a532374bb6e.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Jame Gumb",
          age: "36",
          sex: "Male",
          phone: "888-0000",
          email: "skinned@email.com",
          tag_line: "'Put the lotion in the basket'",
          image: "http://bh-s2.azureedge.net/bh-uploads/2016/01/Buffalo_Bill_House_03-735x525.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Olive Oyl",
          age: "32",
          sex: "Female",
          phone: "309-2198",
          email: "olive@email.com",
          tag_line: "'I don't eat spinach'",
          image: "https://i.pinimg.com/originals/49/4f/b6/494fb69b84bc559029737b792a3953aa.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Annie Wilkes",
          age: "47",
          sex: "Female",
          phone: "405-2954",
          email: "annie@email.com",
          tag_line: "'You dirty bird'",
          image: "http://theycutthepower.com/wp-content/uploads/2014/06/Annie-Wilkes-Misery-3.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Spuds Mackenzie",
          age: "22",
          sex: "Male",
          phone: "406-9254",
          email: "spuds@email.com",
          tag_line: "'Hey, I'm a dog!'",
          image: "http://images.mentalfloss.com/sites/default/files/styles/insert_main_wide_image/public/spudsmackenzie.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Taylor Swift",
          age: "27",
          sex: "Female",
          phone: "206-9245",
          email: "swift@email.com",
          tag_line: "'I stay out too late'",
          image: "http://www.billboard.com/files/styles/article_main_image/public/media/taylor-swift-2014-sarah-barlow-billboard-650.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Serena Williams",
          age: "36",
          sex: "Female",
          phone: "906-1245",
          email: "sw@email.com",
          tag_line: "'Tennis anyone?'",
          image: "http://www.heelshield.com/wp-content/uploads/2012/08/serena-williams-victoria-beckham-red-dress-david-letterman-2012-beauty-and-the-beat-blog.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Fishy Freddy",
          age: "28",
          sex: "Male",
          phone: "106-7245",
          email: "ff@email.com",
          tag_line: "'Just fishing around for a good time'",
          image: "http://laoblogger.com/images/animated-fish-clipart-for-mobile-7.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Rachel Green",
          age: "30",
          sex: "Female",
          phone: "776-1324",
          email: "rg@email.com",
          tag_line: "'Being alone sucks'",
          image: "http://images2.fanpop.com/images/photos/5300000/Rachel-Green-Friends-tv-characters-5385847-460-346.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Holly Golightly",
          age: "24",
          sex: "Female",
          phone: "726-1245",
          email: "hg@email.com",
          tag_line: "'It may be normal, darling; but I'd rather be natural'",
          image: "https://evesreellife.files.wordpress.com/2013/03/icon_opt.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Walter White",
          age: "50",
          sex: "Male",
          phone: "226-5401",
          email: "heisenberg@email.com",
          tag_line: "'I'm the one who knocks'",
          image: "https://images.moviepilot.com/image/upload/c_fill,h_470,q_auto:good,w_620/iifttghw2vaogdfd3sdn.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Zombie Nicole",
          age: "25",
          sex: "Female",
          phone: "746-1481",
          email: "nicole@email.com",
          tag_line: "'Recently divorced girl nextdoor'",
          image: "http://www.fancypantsstore.com/ekmps/shops/fancypantsstore/images/Zombie-Bride-[1]-448-p.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Phil McGraw",
          age: "67",
          sex: "Male",
          phone: "648-2711",
          email: "drphil@email.com",
          tag_line: "'And how's that working for ya?'",
          image: "http://www.tvovermind.com/wp-content/uploads/2017/02/Dr-Phil_Show_Harpo-670x388.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        },
        {name: "Lady Gaga",
          age: "31",
          sex: "Female",
          phone: "899-5500",
          email: "gaga@email.com",
          tag_line: "'Be unique!!'",
          image: "https://pbs.twimg.com/profile_images/833109600660512772/ss9-ojz7.jpg",
          createdAt: Date.now(), 
          updatedAt: Date.now()
        }
  ])];
  },
  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('Users');
  }
};