'use strict';

module.exports = {
  up: (queryInterface, Sequelize)  => {
    return queryInterface.bulkInsert('users', [
        { first_name: "Wan",
          last_name: "Valdez",
          sex: "Male",
          age: 47,
          tag_line: "Who is your daddy?",
          email: "wanvaldez@pimpinstrong.com",
          sms_phone: "555.1234",
          profile_pic: "https://www.pinterest.com/pin/11399805284338369/"
        },
        { first_name: "Jim",
          last_name: "Bailey",
          sex: "Male",
          age: 34,
          tag_line: "Whatever",
          email: "jim@email.com",
          sms_phone: "756.8990",
          profile_pic: "https://s-i.huffpost.com/gen/1065394/images/o-DRAG-QUEENS-facebook.jpg"
        },
        { first_name: "Warrior",
          last_name: "Princess",
          sex: "Female",
          age: 35,
          tag_line: "Looking for a battle",
          email: "xena@email.com",
          sms_phone: "123.3456",
          profile_pic: "https://vignette4.wikia.nocookie.net/warriorprincess/images/5/59/Xena_warrior_princess_by_xena_96-d56o27k.jpg/revision/latest?cb=20130815215113https://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpg"
        },
        { first_name: "Todd",
          last_name: "Jones",
          sex: "Male",
          age: 40,
          tag_line: "Hey there!!",
          email: "toad@email.com",
          sms_phone: "556.7890",
          profile_pic: "https://static.wixstatic.com/media/a6f4a9_c7c670f8ba724db0a07cf85da442d7e4~mv2.jpg"
        },
        { first_name: "Jared",
          last_name: "Fogle",
          sex: "Male",
          age: 40,
          tag_line: "How old r U?",
          email: "jared@email.com",
          sms_phone: "334.7878",
          profile_pic: "https://the-hollywood-gossip-res.cloudinary.com/iu/s--FpbYh7Gu--/t_xlarge_p/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1489513996/jared-fogle-in-a-bowtie.jpg"
        },
        { first_name: "Popcorn",
          last_name: "Sutton",
          sex: "Male",
          age: 65,
          tag_line: "Know a good lawyer?",
          email: "pop@email.com",
          sms_phone: "908-7878",
          profile_pic: "http://media-cdn.timesfreepress.com/img/photos/2014/06/05/866912_t300_t755_he12b112dc0f2a87c390507e9c8ab5039eedb0fe8.JPG"
        },
        { first_name: "Bob",
          last_name: "Marley",
          sex: "Male",
          age: 36,
          tag_line: "It's natural",
          email: "bob@email.com",
          sms_phone: "420.1212",
          profile_pic: "https://i.pinimg.com/736x/7a/dc/ba/7adcba2fde48dab0adfdcc3efcf8e879--musique-reggae-bob-marley.jpg"
        },
        { first_name: "Jack",
          last_name: "Daniels",
          sex: "Male",
          age: 24,
          tag_line: "I need to grow up",
          email: "jack@email.com",
          sms_phone: "777.4501",
          profile_pic: "https://katieholt1.files.wordpress.com/2010/10/oslo_passout.jpg"
        },
        { first_name: "Candy",
          last_name: "Cane",
          sex: "Female",
          age: 23,
          tag_line: "Yes",
          email: "sugar@email.com",
          sms_phone: "444.9988",
          profile_pic: "https://img00.deviantart.net/2892/i/2008/094/2/4/drug_girl_by_aurorabeaupre.jpg"
        },
        { first_name: "Granny",
          last_name: "Moses",
          sex: "Female",
          age: 80,
          tag_line: "$&!% the police",
          email: "granny@email.com",
          sms_phone: "912.3900",
          profile_pic: "https://i.pinimg.com/736x/63/f9/ea/63f9eaf4ff430456106e22abb9732d7b--irene-ryan-ryan-oneal.jpg"
        },
        { first_name: "Billy",
          last_name: "Graham",
          sex: "Male",
          age: 98,
          tag_line: "God is watching",
          email: "will@email.com",
          sms_phone: "666.6666",
          profile_pic: "https://i.pinimg.com/736x/63/f9/ea/63f9eaf4ff430456106e22abb9732d7b--irene-ryan-ryan-oneal.jpg"
        },
        { first_name: "Angelina",
          last_name: "Jolie",
          sex: "Female",
          age: 42,
          tag_line: "Know a good baby sitter",
          email: "ang@email.com",
          sms_phone: "355.6700",
          profile_pic: "https://www.thesun.co.uk/wp-content/uploads/2016/10/nintchdbpict000160735799.jpg?w=640"
          },
        { first_name: "Hunter",
          last_name: "Thompson",
          sex: "Male",
          age: 65,
          tag_line: "I need a drink",
          email: "coke@email.com",
          sms_phone: "088.9999",
          profile_pic: "https://www.thesun.co.uk/wp-content/uploads/2016/10/nintchdbpict000160735799.jpg?w=640"
        },
        { first_name: "Elmer",
          last_name: "Fudd",
          sex: "Male",
          age: 35,
          tag_line: "I work for PETA",
          email: "fud@email.com",
          sms_phone: "705.0139",
          profile_pic: "https://static.comicvine.com/uploads/original/11/111746/4352026-4927658174_981e6cd63e_z.jpg"
          },
        { first_name: "Casey",
          last_name: "Anthony",
          sex: "Female",
          age: 31,
          tag_line: "Where is my daughter?",
          email: "kc@email.com",
          sms_phone: "701.1257",
          profile_pic: "https://static.comicvine.com/uploads/original/11/111746/4352026-4927658174_981e6cd63e_z.jpg"
        },
        { first_name: "Snoop",
          last_name: "Dawg",
          sex: "Male",
          age: 46,
          tag_line: "I never inhale",
          email: "smoke@email.com",
          sms_phone: "913.4200",
          profile_pic: "http://www.chartattack.com/wp-content/uploads/2016/10/snoop-dogg-marijuana.jpg"
        },
        { first_name: "Martha",
          last_name: "Stewart",
          sex: "Female",
          age: 70,
          tag_line: "What's insider trading?",
          email: "foodie@email.com",
          sms_phone: "501.9930",
          profile_pic: "http://a.abcnews.com/images/Entertainment/GTY_martha_stewart_sk_140306_16x9_608.jpg"
        },
        { first_name: "Jim",
          last_name: "Morrison",
          sex: "Male",
          age: 27,
          tag_line: "I am the lizard king",
          email: "jim@email.com",
          sms_phone: "409.1970",
          profile_pic: "http://i.axs.com/2014/08/promoted-media-optimized_53e3a6f8954c3.jpg"
        },
        { first_name: "Kate",
          last_name: "Gosselin",
          sex: "Female",
          age: 42,
          tag_line: "Where are my kids?",
          email: "kateplus8@email.com",
          sms_phone: "222.1020",
          profile_pic: "http://images.gawker.com/17iuol0zjbta5jpg/original.jpg"
        },
        { first_name: "Betty",
          last_name: "Bottle",
          sex: "Female",
          age: 25,
          tag_line: "I'll drink that!",
          email: "betty@email.com",
          sms_phone: "191.1209",
          profile_pic: "http://tarabliss.com.au/wp-content/uploads/2013/03/PGG2P.jpg"
        },
        { first_name: "Janis",
          last_name: "Joplin",
          sex: "Female",
          age: 27,
          tag_line: "Hey Man!",
          email: "janis@email.com",
          sms_phone: "235.6509",
          profile_pic: "http://d1wl13ohcvociy.cloudfront.net/wp-content/uploads/2015/09/tumblr_meyke7bh8u1rwkvi9o1_500.jpg"
        },
        { first_name: "Tina",
          last_name: "Turner",
          sex: "Female",
          age: 65,
          tag_line: "What's love gotta do with it?",
          email: "tina@email.com",
          sms_phone: "222.5126",
          profile_pic: "https://i.pinimg.com/originals/46/cb/bf/46cbbf36cedb467f8b3d9a532374bb6e.jpg"
        },
        { first_name: "Jame",
          last_name: "Gumb",
          sex: "Male",
          age: 36,
          tag_line: "Put the lotion in the basket",
          email: "skinned@email.com",
          sms_phone: "888.0000",
          profile_pic: "http://bh-s2.azureedge.net/bh-uploads/2016/01/Buffalo_Bill_House_03-735x525.jpg"
        },
        { first_name: "Olive",
          last_name: "Oyl",
          sex: "Female",
          age: 32,
          tag_line: "I don't eat spinach",
          email: "olive@email.com",
          sms_phone: "309.2198",
          profile_pic: "https://i.pinimg.com/originals/49/4f/b6/494fb69b84bc559029737b792a3953aa.jpg"
        },
        { first_name: "Annie",
          last_name: "Wilkes",
          sex: "Female",
          age: 47,
          tag_line: "You dirty bird",
          email: "annie@email.com",
          sms_phone: "405.2954",
          profile_pic: "http://theycutthepower.com/wp-content/uploads/2014/06/Annie-Wilkes-Misery-3.jpg"
        },
        { first_name: "Spuds",
          last_name: "Mackenzie",
          sex: "Male",
          age: 22,
          tag_line: "Hey, I'm a dog!",
          email: "spuds@email.com",
          sms_phone: "406.9254",
          profile_pic: "http://images.mentalfloss.com/sites/default/files/styles/insert_main_wide_image/public/spudsmackenzie.jpg"
        },
        { first_name: "Taylor",
          last_name: "Swift",
          sex: "Female",
          age: 27,
          tag_line: "I stay out too late",
          email: "swift@email.com",
          sms_phone: "206.9245",
          profile_pic: "http://www.billboard.com/files/styles/article_main_image/public/media/taylor-swift-2014-sarah-barlow-billboard-650.jpg"
        },
        { first_name: "Serena",
          last_name: "Williams",
          sex: "Female",
          age: 36,
          tag_line: "Tennis anyone?",
          email: "sw@email.com",
          sms_phone: "906.1245",
          profile_pic: "http://www.heelshield.com/wp-content/uploads/2012/08/serena-williams-victoria-beckham-red-dress-david-letterman-2012-beauty-and-the-beat-blog.jpg"
        },
        { first_name: "Fishy",
          last_name: "Freddy",
          sex: "Male",
          age: 28,
          tag_line: "Just fishing around for a good time",
          email: "ff@email.com",
          sms_phone: "106.7245",
          profile_pic: "http://laoblogger.com/images/animated-fish-clipart-for-mobile-7.jpg"
        },
        { first_name: "Rachel",
          last_name: "Green",
          sex: "Female",
          age: 30,
          tag_line: "Being alone sucks",
          email: "rg@email.com",
          sms_phone: "776.1324",
          profile_pic: "http://images2.fanpop.com/images/photos/5300000/Rachel-Green-Friends-tv-characters-5385847-460-346.jpg"
        },
        { first_name: "Holly",
          last_name: "Golightly",
          sex: "Female",
          age: 24,
          tag_line: "It may be normal, darling; but I'd rather be natural",
          email: "hg@email.com",
          sms_phone: "726.1245",
          profile_pic: "https://evesreellife.files.wordpress.com/2013/03/icon_opt.jpg"
        },
        { first_name: "Walter",
          last_name: "White",
          sex: "Male",
          age: 50,
          tag_line: "I'm the one who knocks",
          email: "heisenberg@email.com",
          sms_phone: "226.5401",
          profile_pic: "https://images.moviepilot.com/image/upload/c_fill,h_470,q_auto:good,w_620/iifttghw2vaogdfd3sdn.jpg"
        },
        { first_name: "Zombie",
          last_name: "Nicole",
          sex: "Female",
          age: 25,
          tag_line: "Recently divorced girl nextdoor",
          email: "nicole@email.com",
          sms_phone: "746.1481",
          profile_pic: "http://www.fancypantsstore.com/ekmps/shops/fancypantsstore/images/Zombie-Bride-[1]-448-p.jpg"
        },
        { first_name: "Phil",
          last_name: "McGraw",
          sex: "Male",
          age: 67,
          tag_line: "And how's that working for ya?",
          email: "drphil@email.com",
          sms_phone: "648.2711",
          profile_pic: "http://www.tvovermind.com/wp-content/uploads/2017/02/Dr-Phil_Show_Harpo-670x388.jpg"
        },
        { first_name: "Lady",
          last_name: "Gaga",
          sex: "Female",
          age: 31,
          tag_line: "Be Unique!!",
          email: "gaga@email.com",
          sms_phone: "899.5500",
          profile_pic: "https://pbs.twimg.com/profile_images/833109600660512772/ss9-ojz7.jpg"
        }
    ]);
  },
  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('Users');
  }
};